"""Generate `.kiro/specs/<agent>/{requirements,design,tasks}.md` from `AGENT_MANIFEST`.

Public API:
  • `export_kiro_specs(out_root: Path) -> dict` — write all 28 spec dirs
  • `kiro_spec_for_agent(entry: dict) -> dict[filename, content]` — one agent

Run from CLI:
    python -m app.integrations.kiro.exporter
or via the FastAPI route:
    POST /api/v1/integrations/kiro/export

The CLI form is the one Kiro IDE itself can wire to a pre-commit Hook so
specs always reflect the current code. The HTTP form is the one a
developer runs from the demo UI ("watch us regenerate Kiro specs live").
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# =============================================================================
# Per-agent spec generation
# =============================================================================


def _requirements_md(entry: dict[str, Any]) -> str:
    name = entry["name"]
    parent = entry.get("parent") or "(top-level)"
    role = entry.get("role") or ""
    description = entry.get("description") or ""
    is_llm = entry.get("is_llm_backed", True)
    schema_in = entry.get("input_schema", "?")
    schema_out = entry.get("output_schema", "?")

    primary = entry.get("primary_model") or {}
    fallback = entry.get("fallback_model") or {}
    impl_note = (
        f"  - LLM-backed via Bedrock {primary.get('size', 'sonnet')} "
        f"({primary.get('role', 'reasoning')}) by default; "
        f"fallback model `{fallback.get('size', 'sonnet')}` on retry."
        if is_llm else
        "  - Deterministic Python implementation; no LLM call."
    )

    return f"""# Requirements — `{name}`

> Generated from ClinCase `AGENT_MANIFEST` at {datetime.now(UTC).isoformat()}.
> Edit the agent's source under `backend/app/agents/{parent if parent != '(top-level)' else name}/` —
> this file is regenerated by `python -m app.integrations.kiro.exporter`.

## Identity

- **Name:** `{name}`
- **Parent:** `{parent}`
- **Role:** {role}
- **Description:** {description}

## User stories

- **US-{name}-1** As a payer-side reviewer, I want this agent to produce
  `{schema_out}` from `{schema_in}` so that the determination chain is
  reproducible and auditable per CMS-0057-F § IV.D.

- **US-{name}-2** As a compliance officer, I want every invocation of
  `{name}` to write an `agent_runs` row with input/output/model_id/tokens
  so that any decision can be reconstructed within 12 seconds.

- **US-{name}-3** As an oncologist or care-coordinator, I want
  `{name}`'s output to cite specific policy sections (or clinical evidence)
  so that the rationale satisfies CMS-0057-F § IV.B.2 specific-reason
  notice and aligns with NCCN guidelines.

## EARS acceptance criteria

- **EARS-{name}-1** WHEN `{name}` receives a `{schema_in}` payload, IT SHALL
  emit a Pydantic-validated `{schema_out}` within the per-agent budget
  ceiling (USD ≤ $5/case shared budget; tokens bounded per invocation).

- **EARS-{name}-2** WHEN `{name}` cannot produce a valid `{schema_out}` after
  `max_iterations` attempts, IT SHALL raise `AgentExhausted` rather than
  return malformed output.

- **EARS-{name}-3** WHEN `{name}` runs as a sub-agent (parent != null), IT
  SHALL share the parent's `AgentContext` so cost/token/latency budgets
  are accounted at the case level.

- **EARS-{name}-4** WHEN any input guardrail returns `BLOCK`, `{name}` SHALL
  raise `InputBlocked` and emit a `guardrail_blocked` span event.

## Compliance hooks

- CMS-0057-F § IV.D — every invocation persisted to `agent_runs`.
- HIPAA — PHI guardrails redact PHI from prompts to non-Bedrock LLMs.
- CA SB 1120 — adverse determinations route through `review_gate` (not this agent's responsibility, but `{name}` MUST emit `triggered_hitl` correctly when low-confidence).

## Implementation notes

{impl_note}

- Input schema:  `{schema_in}` (Pydantic v2)
- Output schema: `{schema_out}` (Pydantic v2)
- Max iterations: {entry.get('max_iterations', 1)}
- Quality threshold: {entry.get('quality_threshold', 0.0)}
"""


def _design_md(entry: dict[str, Any]) -> str:
    name = entry["name"]
    parent = entry.get("parent") or None
    schema_in = entry.get("input_schema", "?")
    schema_out = entry.get("output_schema", "?")
    schema_in_json = json.dumps(entry.get("input_schema_json", {}), indent=2)[:1500]
    schema_out_json = json.dumps(entry.get("output_schema_json", {}), indent=2)[:1500]
    in_guardrails = entry.get("input_guardrails", [])
    out_guardrails = entry.get("output_guardrails", [])

    parent_section = f"""
This agent is a **sub-agent** of `{parent}`. It shares the parent's
`AgentContext`, including:
  - `BudgetTracker` — per-case $5 / 600K-token ceiling
  - `TraceSink` — `PostgresTraceSink` in production, `InMemoryTraceSink` in tests
  - `WorkingMemory` — case-scoped scratch
  - `parent_span_id` — wires this span under the parent in the AgentTrace tree
""" if parent else """
This agent is a **top-level orchestrator**. Its output is one of the
seven nodes in the LangGraph DAG (`app/graph/build.py`).
"""

    return f"""# Design — `{name}`

> Generated from ClinCase `AGENT_MANIFEST` at {datetime.now(UTC).isoformat()}.

## Architecture
{parent_section}

## Input schema (`{schema_in}`)

```json
{schema_in_json}
```

## Output schema (`{schema_out}`)

```json
{schema_out_json}
```

## Guardrails

### Input

{chr(10).join(f"- `{g.get('name')}`: {g.get('purpose', '')}" for g in in_guardrails) or "- _(none configured)_"}

### Output

{chr(10).join(f"- `{g.get('name')}`: {g.get('purpose', '')}" for g in out_guardrails) or "- _(none configured)_"}

## Lifecycle (inherited from `Agent[I, O]`)

1. Validate input against `{schema_in}` (Pydantic).
2. Cache lookup (sha256 of input + schema version + organization_id).
3. Input guardrails (PHI mask · token budget · custom).
4. Budget reservation against case-level `BudgetTracker`.
5. Act — LLM call OR `_execute_deterministic`.
6. Parse output into `{schema_out}` with retry-on-failure (Haiku→Sonnet escalation).
7. Output guardrails (citation completeness · custom).
8. Reflection (if `quality_threshold > 0`): grader scores; below-threshold retries.
9. Cache store on success.
10. Emit `AgentTrace` span; persist `agent_runs` row.

## Models

- **Primary:** `{(entry.get('primary_model') or {}).get('size', 'deterministic')}` ({(entry.get('primary_model') or {}).get('role', 'n/a')})
- **Fallback:** `{(entry.get('fallback_model') or {}).get('size', 'auto-escalate')}`

## Telemetry

Every invocation emits to `app/api/metrics.py` Prometheus counters:
- `clincase_agent_invocations_total{{agent="{name}",status=...}}`
- `clincase_agent_latency_ms_p99`
- `clincase_llm_tokens_total{{model_id=...}}`
- `clincase_llm_cost_usd_total`

## Failure modes

- `BudgetExceeded` — caller's case-level budget exhausted before this agent ran.
- `InputBlocked` / `OutputBlocked` — a guardrail rejected the payload.
- `AgentExhausted` — schema parse failed after `max_iterations` retries.
- Bedrock 5xx — `ModelRouter.escalate(...)` switches to fallback on retry.
"""


def _tasks_md(entry: dict[str, Any]) -> str:
    name = entry["name"]
    parent = entry.get("parent") or None
    is_llm = entry.get("is_llm_backed", True)

    pkg_path = (
        f"backend/app/agents/{parent}/sub_agents/{name}.py"
        if parent else f"backend/app/agents/{name}/orchestrator.py"
    )

    llm_specific_tasks = """
- [ ] Author `system_prompt` in `backend/app/prompts/{parent}/sub_agents/{name}.txt` (or `{name}.txt` for orchestrators).
- [ ] Set `primary_model` to the appropriate `ModelSpec` (`SONNET_REASONING`, `HAIKU_LITE`, etc.).
- [ ] If output requires reflection, set `quality_threshold > 0` and reuse `LLMGrader` default.
- [ ] Add a `phi_sanitizer` input guardrail when prompt receives raw FHIR.
""" if is_llm else """
- [ ] Implement `_execute_deterministic(input, ctx) -> output` in `{file}`.
- [ ] Set `primary_model = None` so the framework knows to skip the LLM path.
"""

    return f"""# Tasks — `{name}`

> Generated from ClinCase `AGENT_MANIFEST` at {datetime.now(UTC).isoformat()}.

## Implementation tasks

- [ ] Define `{entry.get('input_schema', '?')}` (input) and `{entry.get('output_schema', '?')}` (output) in the package's `schemas.py`.
- [ ] Subclass `Agent[InputSchema, OutputSchema]`, declaring required ClassVars (`name`, `parent`, `role`, `description`).
- [ ] Place implementation in `{pkg_path}`.
{llm_specific_tasks.format(parent=parent or name, name=name, file=pkg_path)}

## Test tasks

- [ ] Add a contract test under `backend/tests/agents/test_{name}.py`.
- [ ] Use `tests/fixtures/` cases that exercise APPROVE / DENY / REFER paths.
- [ ] Assert: schema validity, citations populated, budget consumed, span persisted.
- [ ] Assert HITL routing where `confidence < 0.75`.

## Ops tasks

- [ ] No K8s changes required — auto-discovered by `app/agents/manifest.py`.
- [ ] No metrics wiring required — `Agent.invoke()` emits Prometheus counters automatically.
"""


def kiro_spec_for_agent(entry: dict[str, Any]) -> dict[str, str]:
    """Return `{filename: content}` for one agent."""
    return {
        "requirements.md": _requirements_md(entry),
        "design.md": _design_md(entry),
        "tasks.md": _tasks_md(entry),
    }


# =============================================================================
# Bulk export
# =============================================================================


def _index_md(parent_entries: list[dict[str, Any]], total_subs: int) -> str:
    rows = []
    for p in parent_entries:
        rows.append(f"- `{p['name']}` — {p.get('description', '')[:80]}")
        for s in p.get("sub_agents", []):
            rows.append(f"  - `{p['name']}.{s['name']}`")
    return f"""# ClinCase — `.kiro/specs/` index

This directory is the Kiro-IDE-compatible specification of every ClinCase
agent. The tree is **generated** from `app.agents.manifest.AGENT_MANIFEST`;
do not edit by hand. Re-run:

```bash
python -m app.integrations.kiro.exporter
# or
curl -XPOST localhost:8000/api/v1/integrations/kiro/export -H "Authorization: Bearer ..."
```

## Structure

```
.kiro/
├── README.md                  ← this file
└── specs/
    ├── <parent>/
    │   ├── requirements.md   ← EARS acceptance criteria + user stories
    │   ├── design.md         ← schemas, lifecycle, guardrails
    │   ├── tasks.md          ← checkable build steps
    │   └── sub_agents/
    │       └── <sub>/
    │           ├── requirements.md
    │           ├── design.md
    │           └── tasks.md
    └── ...
```

## Inventory

- **{len(parent_entries)} parent agents** (LangGraph nodes)
- **{total_subs} sub-agents** (15 LLM-backed · 6 deterministic)
- **3 reflection-enabled** sub-agents (quality_threshold > 0)

{chr(10).join(rows)}

## How Kiro picks this up

1. Place `.kiro/specs/` at repo root (already done by exporter).
2. Open repo in Kiro IDE.
3. Kiro auto-loads specs and surfaces them in the side panel.
4. Edit a `requirements.md`; the Hook regenerates the corresponding agent
   skeleton in `backend/app/agents/...`.
5. Commit. The CI Hook validates each spec against the live
   `AGENT_MANIFEST` and fails the build if drift is detected.

> Why this matters: Kiro's published healthcare references to date are
> life-sciences (the "3-week drug discovery agent" AWS post). ClinCase
> publishes 28 specs in one repo — the first comprehensive PA-domain
> Kiro reference.
"""


def export_kiro_specs(out_root: Path | None = None) -> dict[str, Any]:
    """Materialize the `.kiro/specs/` tree on disk.

    Default `out_root` = repo root (3 levels above this file). Caller can
    override (e.g. tests writing to a tmp dir).

    Returns a summary {n_parents, n_subs, files_written}.
    """
    from app.agents.manifest import AGENT_MANIFEST

    if out_root is None:
        out_root = Path(__file__).resolve().parents[4]  # repo root
    kiro_root = out_root / ".kiro"
    specs_root = kiro_root / "specs"
    specs_root.mkdir(parents=True, exist_ok=True)

    total_subs = sum(len(p.get("sub_agents", [])) for p in AGENT_MANIFEST)

    # Index file
    (kiro_root / "README.md").write_text(_index_md(AGENT_MANIFEST, total_subs), encoding="utf-8")

    files_written = 1

    for parent in AGENT_MANIFEST:
        p_dir = specs_root / parent["name"]
        p_dir.mkdir(parents=True, exist_ok=True)
        for filename, content in kiro_spec_for_agent(parent).items():
            (p_dir / filename).write_text(content, encoding="utf-8")
            files_written += 1
        # Sub-agents
        sub_root = p_dir / "sub_agents"
        sub_root.mkdir(parents=True, exist_ok=True)
        for sub in parent.get("sub_agents", []):
            s_dir = sub_root / sub["name"]
            s_dir.mkdir(parents=True, exist_ok=True)
            for filename, content in kiro_spec_for_agent(sub).items():
                (s_dir / filename).write_text(content, encoding="utf-8")
                files_written += 1

    return {
        "n_parents": len(AGENT_MANIFEST),
        "n_sub_agents": total_subs,
        "files_written": files_written,
        "kiro_root": str(kiro_root),
    }


# =============================================================================
# CLI entry point
# =============================================================================


def _main() -> None:
    import json
    summary = export_kiro_specs()
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    _main()
