"""OncoTwin → ClinCase handoff.

A clinician-reviewed twin alert becomes a ClinCase prior-authorisation case:

  twin evidence ──► treatment/regimen context ──► FHIR bundle (incl. a FHIR
  RiskAssessment carrying the twin's prediction) + DRAFT physician note
  ──► ClinCase's own policy corpus previewed through ClinCase's
      keyword_filter agent ──► ClinCase case created through the SAME
      `create_case` code path as POST /api/v1/cases ──► the clinician runs
      the unchanged 7-agent ClinCase pipeline (with its HITL gate) from the
      existing case page.

Nothing here submits anything to a payer; nothing runs without a clinician
having accepted or chosen to investigate the alert first.
"""
from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Any

from app.oncotwin import SYNTHETIC_TAG
from app.oncotwin.fhir.mapping import event_to_fhir, fhir_id, observation_to_fhir, patient_to_fhir
from app.oncotwin.records import PatientRecord, day_to_iso
from app.oncotwin.signals import SIGNALS
from app.oncotwin.simulator.regimens import REGIMENS

PEGFILGRASTIM = {
    "name": "pegfilgrastim", "hcpcs_code": "J2506", "j_code": "J2506",
    "dose": "6 mg subcutaneously once per chemotherapy cycle, 24–72 h after chemotherapy",
    "frequency": "once per chemotherapy cycle",
    "intent": "supportive — secondary prophylaxis of febrile neutropenia",
}
INFECTION_GROUPS = {"temperature", "resting_hr", "hrv_sdnn", "spo2", "neutrophil"}
BUNDLE_EVENT_KINDS = ("diagnosis", "pathology", "genomics", "imaging", "careplan", "medication_request",
                      "chemo_dose", "gcsf_dose", "performance_status", "encounter", "antibiotic")


def suggest_treatment(record: PatientRecord, alert: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """Suggest what the PA request would be for — the clinician can override it."""
    reg = REGIMENS[record.profile.regimen_code]
    groups = {c["group"] for c in alert["prediction"]["contributors"][:4] if c["logit"] > 0}
    if groups & INFECTION_GROUPS and reg.myelotox >= 0.3:
        return dict(PEGFILGRASTIM), (
            "Infection/neutropenia-pattern alert on a myelosuppressive regimen — secondary G-CSF prophylaxis "
            "for the next cycle is the treatment decision most likely to need prior authorisation.")
    main = reg.drugs[0]
    return {"name": main.name, "intent": f"continuation of {reg.code} with clinician-directed modification",
            "frequency": f"every {reg.cycle_days} days"}, (
        f"No supportive-care PA indicated by the evidence pattern; package prepared for continuation of {reg.code}.")


def _note(record: PatientRecord, alert: dict[str, Any], requested: dict[str, Any]) -> str:
    p = record.profile
    reg = REGIMENS[p.regimen_code]
    ev = alert["evidence"]
    changed = "; ".join(w["text"] for w in ev["what_changed"][:4]) or "no single signal beyond 1.5 SD"
    action = alert["actions"][-1] if alert.get("actions") else None
    tx = alert["state_summary"]["treatment"]
    anc = tx.get("anc_estimate") or {}
    reviewed = ""
    if action:
        reviewed = (f"Reviewed by {action['user_email']} ({action['role']}) — decision: {action['action']}"
                    + (f"; note: {action['note']}" if action.get("note") else "") + ".\n\n")
    return (
        "DRAFT — generated by OncoTwin from digital-twin evidence. Clinician review and editing required "
        "before any submission. Synthetic demonstration patient.\n\n"
        f"{p.age}-year-old {p.sex} with {p.cancer}, stage {p.stage} "
        f"({', '.join(f'{k} {v}' for k, v in p.biomarkers.items())}), on {reg.name}; "
        f"cycle {tx['cycle']} (day {tx['day_of_cycle']}); G-CSF this cycle: {'yes' if tx['gcsf_this_cycle'] else 'no'}.\n\n"
        f"On Day {alert['as_of_day']} the OncoTwin digital twin raised {alert['tier']}: {ev['headline']}. "
        f"Changes versus the patient's personal baseline: {changed}. "
        f"Twin-estimated ANC {anc.get('mean', 'n/a')} ×10³/µL. {ev['period']['text']}\n\n"
        f"{reviewed}"
        f"Request: {requested['name']} — {requested.get('dose', '')} ({requested.get('intent', '')}). "
        f"Next planned cycle: Day {tx.get('next_dose_day') or 'per plan'}.\n\n"
        f"Reviewer considerations generated by the twin: {' | '.join(ev['review'][:3])}"
    )


def build_clincase_bundle(record: PatientRecord, alert: dict[str, Any]) -> dict[str, Any]:
    """Focused FHIR bundle for ClinCase: clinical context + twin evidence + RiskAssessment."""
    day = alert["as_of_day"]
    pid = record.profile.patient_id
    synth = record.profile.synthetic
    evidence_ids = {e["observation_id"] for e in alert["evidence"]["evidence"] if e.get("observation_id")}
    resources = [patient_to_fhir(record.profile)]
    resources += [event_to_fhir(e, pid, synth) for e in record.events_until(day) if e.kind in BUNDLE_EVENT_KINDS]
    for o in record.observations_until(day):
        if o.id in evidence_ids or (SIGNALS[o.signal].category == "lab" and o.day >= day - 21):
            resources.append(observation_to_fhir(o, pid, synth))
    model = alert["prediction"]["model"]
    risk = {
        "resourceType": "RiskAssessment", "id": fhir_id(f"oncotwin-risk-{alert['id']}"), "status": "final",
        "subject": {"reference": f"Patient/{fhir_id(pid)}"}, "occurrenceDateTime": day_to_iso(day, 23, 59),
        "method": {"text": f"OncoTwin {model['model_id']} v{model['version']} (artifact sha256 {model['artifact_sha256'][:16]}…)"},
        "basis": [{"reference": f"Observation/{fhir_id(oid)}"} for oid in sorted(evidence_ids)],
        "prediction": [{
            "outcome": {"text": "OT-ACUTE-7: unplanned ED visit / admission for a CMS OP-35 chemotherapy-related condition"},
            "probabilityDecimal": alert["risk"],
            "whenRange": {"high": {"value": 7, "unit": "days", "system": "http://unitsofmeasure.org", "code": "d"}},
            "rationale": alert["evidence"]["why"][:900],
        }],
        "note": [{"text": "Clinical decision support output; not a diagnosis. Reviewed by a clinician before handoff."}],
    }
    if synth:
        risk["meta"] = {"tag": [SYNTHETIC_TAG]}
    resources.append(risk)
    return {"resourceType": "Bundle", "type": "collection", "id": fhir_id(f"oncotwin-handoff-{alert['id']}"),
            "entry": [{"fullUrl": f"urn:uuid:{r['resourceType']}-{r['id']}", "resource": r} for r in resources]}


async def policy_preview(payer_id: str, treatment_name: str, organization_id: str, alert_id: str) -> list[dict[str, Any]]:
    """Run ClinCase's own keyword_filter agent (full agent lifecycle, in-memory trace)."""
    from app.agents.framework import InMemoryTraceSink, new_agent_context
    from app.agents.policy_retriever.schemas import KeywordFilterInput
    from app.agents.policy_retriever.sub_agents.keyword_filter import keyword_filter

    ctx = new_agent_context(case_id=f"oncotwin-handoff-{alert_id}", organization_id=organization_id,
                            trace_sink=InMemoryTraceSink())
    res = await keyword_filter.invoke(KeywordFilterInput(payer_id=payer_id, treatment_name=treatment_name), ctx=ctx)
    return [{"policy_id": c.policy_id, "policy_title": c.policy_title, "section_heading": c.section_heading,
             "page_number": c.page_number, "excerpt": c.section_text[:280] + ("…" if len(c.section_text) > 280 else "")}
            for c in res.output.candidates]


async def build_package(record: PatientRecord, alert: dict[str, Any], organization_id: str,
                        requested_override: dict[str, Any] | None = None) -> dict[str, Any]:
    requested, rationale = suggest_treatment(record, alert)
    if requested_override:
        requested = {**requested, **{k: v for k, v in requested_override.items() if v}}
        rationale = "Clinician-specified request."
    bundle = build_clincase_bundle(record, alert)
    preview = await policy_preview(record.profile.payer_id, requested["name"], organization_id, alert["id"])
    create_req = {
        "payer_id": record.profile.payer_id,
        "patient_initials": record.profile.label.replace("-", ""),
        "fhir_bundle": bundle,
        "physician_note": _note(record, alert, requested),
        "requested_treatment": requested,
    }
    digest = hashlib.sha256(json.dumps(create_req, sort_keys=True, default=str).encode()).hexdigest()
    return {
        "create_case_request": create_req,
        "requested_treatment_rationale": rationale,
        "policy_preview": preview,
        "policy_preview_note": (
            f"{len(preview)} section(s) of ClinCase's curated policy corpus match {requested['name']} for payer "
            f"'{record.profile.payer_id}'." if preview else
            f"No policy for {requested['name']} / '{record.profile.payer_id}' in ClinCase's curated corpus — "
            "the ClinCase pipeline will be expected to route this case to human review."),
        "package_sha256": digest,
        "bundle_resource_count": len(bundle["entry"]),
        "built_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
    }
