---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clincase-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=clincase-backend
    argocd-image-updater.argoproj.io/api.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/victrvondoom/CLINI-CASE.git
    targetRevision: main
    path: ops/k8s/api
  destination:
    server: https://kubernetes.default.svc
    namespace: clincase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
