/* global window */
// Policy library + diff data.
(function () {
  const POLICIES = [
    {
      id: "aetna-0123",
      payer_id: "aetna",
      title: "Trastuzumab (Herceptin) for HER2+ Breast Cancer",
      number: "0123",
      version: "v2026.1",
      effective: "2026-03-01",
      drug: "Trastuzumab",
      indications: ["HER2+ breast cancer", "metastatic", "early-stage"],
      hasDiff: true,
      summary: "Coverage criteria for trastuzumab in HER2+ breast cancer, including LVEF baseline and concomitant therapy requirements.",
    },
    {
      id: "uhc-onc-00043",
      payer_id: "uhc",
      title: "ONC.00043 — Trastuzumab Biosimilars",
      number: "ONC.00043",
      version: "v2026.0",
      effective: "2026-01-15",
      drug: "Trastuzumab",
      indications: ["HER2+ breast cancer", "biosimilar substitution"],
      hasDiff: false,
      summary: "Step therapy for trastuzumab biosimilars (Ogivri, Trazimera, Kanjinti) before reference product approval.",
    },
    {
      id: "nccn-binv-n-v3",
      payer_id: "nccn",
      title: "NCCN BINV-N: Systemic Therapy for HER2+ Disease",
      number: "BINV-N",
      version: "v3.2026",
      effective: "2026-02-08",
      drug: "Multi-agent",
      indications: ["HER2+ breast cancer", "guideline reference"],
      hasDiff: false,
      summary: "Category 1 guidelines for HER2-targeted systemic therapy, including dual blockade and antibody-drug conjugate sequencing.",
    },
    {
      id: "aetna-0048",
      payer_id: "aetna",
      title: "EGFR-Targeted Therapy in NSCLC",
      number: "0048",
      version: "v2026.0",
      effective: "2026-01-22",
      drug: "Osimertinib",
      indications: ["NSCLC", "EGFR exon 19/21", "T790M+"],
      hasDiff: false,
      summary: "Coverage for first- and later-line EGFR TKIs in advanced NSCLC with EGFR-sensitizing mutations.",
    },
    {
      id: "cigna-0512",
      payer_id: "cigna",
      title: "Pembrolizumab (Keytruda) in Solid Tumors",
      number: "0512",
      version: "v2026.0",
      effective: "2026-02-01",
      drug: "Pembrolizumab",
      indications: ["NSCLC", "melanoma", "MSI-H/dMMR", "TMB-H"],
      hasDiff: false,
      summary: "Multi-indication coverage for pembrolizumab including PD-L1 thresholds and combination regimens.",
    },
    {
      id: "humana-h0247",
      payer_id: "humana",
      title: "CDK4/6 Inhibitors in HR+/HER2− Breast Cancer",
      number: "H0247",
      version: "v2026.0",
      effective: "2026-01-08",
      drug: "Palbociclib / Ribociclib / Abemaciclib",
      indications: ["HR+/HER2− metastatic", "first-line endocrine"],
      hasDiff: false,
      summary: "Coverage for CDK4/6 inhibitors in combination with aromatase inhibitor or fulvestrant.",
    },
  ];

  // Aetna 0123 §4.2 — LVEF window expansion (favorable to patient).
  const DIFF_AETNA_0123 = {
    policy_id: "aetna-0123",
    title: "Aetna 0123 — Trastuzumab (Herceptin) for HER2+ Breast Cancer",
    fromVersion: "v2025.4",
    toVersion: "v2026.1",
    effective: "2026-03-01",
    section: "§4.2 Cardiac function — baseline assessment",
    summary: "LVEF baseline window widened from 60 days → 90 days. Aligns Aetna with NCCN BINV-N v3.2026 and reduces unnecessary repeat echocardiograms.",
    impact: { cases_affected: 1, hint_case_id: "AUTH-2026-1841" },
    consumed_by_agents: ["policy_retriever", "necessity_reasoner", "decision_composer"],
    rows: [
      { kind: "ctx", a: 1,  b: 1,  text: "§4.2 Cardiac function — baseline assessment" },
      { kind: "ctx", a: 2,  b: 2,  text: "" },
      { kind: "ctx", a: 3,  b: 3,  text: "Prior to initiating trastuzumab, the member must have:" },
      { kind: "ctx", a: 4,  b: 4,  text: "" },
      { kind: "ctx", a: 5,  b: 5,  text: "(a) A documented baseline left ventricular ejection fraction" },
      { kind: "del", a: 6,  b: null, text: "    (LVEF) within 60 days of the proposed start date, AND" },
      { kind: "add", a: null, b: 6,  text: "    (LVEF) within 90 days of the proposed start date, AND" },
      { kind: "ctx", a: 7,  b: 7,  text: "(b) LVEF ≥ 50% by echocardiography or MUGA scan, AND" },
      { kind: "ctx", a: 8,  b: 8,  text: "(c) No evidence of NYHA Class III–IV heart failure." },
      { kind: "ctx", a: 9,  b: 9,  text: "" },
      { kind: "del", a: 10, b: null, text: "Repeat LVEF assessment is required if the baseline study" },
      { kind: "del", a: 11, b: null, text: "is older than 60 days at the time of authorization." },
      { kind: "add", a: null, b: 10, text: "Repeat LVEF assessment is required if the baseline study" },
      { kind: "add", a: null, b: 11, text: "is older than 90 days at the time of authorization." },
      { kind: "ctx", a: 12, b: 12, text: "" },
      { kind: "ctx", a: 13, b: 13, text: "§4.3 Concomitant cardiotoxic therapy" },
      { kind: "ctx", a: 14, b: 14, text: "" },
      { kind: "ctx", a: 15, b: 15, text: "Members receiving concurrent anthracyclines must have" },
      { kind: "ctx", a: 16, b: 16, text: "interval LVEF monitoring every 3 months." },
    ],
  };

  window.CLINCASE_POLICIES = {
    POLICIES,
    DIFFS: { "aetna-0123": DIFF_AETNA_0123 },
  };
})();
